apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blurmoji.fullname" . }}-storage-config
  namespace: {{ .Values.global.namespace }}
data:
  CHALLENGE_STORAGE_BACKEND: {{ .Values.config.challengeStorageBackend | quote }}
  CHALLENGE_STORAGE_FILE_PATH: {{ .Values.config.challengeStorageFilePath | quote }}
  REDIS_HOST: "{{ include "blurmoji.fullname" . }}-redis"
  REDIS_PORT: {{ .Values.servicePorts.redis | quote }}
  REDIS_DB: {{ .Values.config.redisDb | quote }}
  REDIS_TTL_SECONDS: {{ .Values.config.redisTtlSeconds | quote }}


