apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blurmoji.fullname" . }}-runtime-config
  namespace: {{ .Values.global.namespace }}
data:
  GAME_ENGINE_SERVICE_BASE_URL: "http://{{ include "blurmoji.fullname" . }}-game-engine:{{ .Values.servicePorts.gameEngine }}"
  EMOJI_CATALOG_SERVICE_BASE_URL: "http://{{ include "blurmoji.fullname" . }}-emoji-catalog:{{ .Values.servicePorts.emojiCatalog }}"
  EMOJI_RENDER_SERVICE_BASE_URL: "http://{{ include "blurmoji.fullname" . }}-emoji-render:{{ .Values.servicePorts.emojiRender }}"
  API_BASE_URL: "http://{{ include "blurmoji.fullname" . }}-gateway:{{ .Values.servicePorts.gateway }}"
