{{- if .Values.infra.gameStateStorage.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "blurmoji.fullname" . }}-game-state-storage
  namespace: {{ .Values.global.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "blurmoji.fullname" . }}-game-state-storage
  template:
    metadata:
      labels:
        app: {{ include "blurmoji.fullname" . }}-game-state-storage
    spec:
      containers:
        - name: game-state-storage
          image: {{ include "blurmoji.gameStateStorageImage" . }}
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.servicePorts.gameStateStorage }}
{{- end }}
