apiVersion: v1
kind: Secret
metadata:
  name: {{ include "blurmoji.fullname" . }}-secret
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  SESSION_COOKIE_SECRET: {{ .Values.secrets.sessionCookieSecret | quote }}
