apiVersion: v1
kind: Service
metadata:
  name: {{ include "blurmoji.fullname" . }}-gateway
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ include "blurmoji.fullname" . }}-gateway
  ports:
    - port: {{ .Values.servicePorts.gateway }}
      targetPort: {{ .Values.servicePorts.gateway }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blurmoji.fullname" . }}-game-engine
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ include "blurmoji.fullname" . }}-game-engine
  ports:
    - port: {{ .Values.servicePorts.gameEngine }}
      targetPort: {{ .Values.servicePorts.gameEngine }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blurmoji.fullname" . }}-emoji-catalog
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ include "blurmoji.fullname" . }}-emoji-catalog
  ports:
    - port: {{ .Values.servicePorts.emojiCatalog }}
      targetPort: {{ .Values.servicePorts.emojiCatalog }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blurmoji.fullname" . }}-emoji-render
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ include "blurmoji.fullname" . }}-emoji-render
  ports:
    - port: {{ .Values.servicePorts.emojiRender }}
      targetPort: {{ .Values.servicePorts.emojiRender }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blurmoji.fullname" . }}-frontend
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ include "blurmoji.fullname" . }}-frontend
  ports:
    - port: {{ .Values.servicePorts.frontend }}
      targetPort: {{ .Values.servicePorts.frontend }}
