apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blurmoji.fullname" . }}-config
  namespace: {{ .Values.global.namespace }}
data:
  INTERNAL_HTTP_TIMEOUT_SECONDS: {{ .Values.config.internalHttpTimeoutSeconds | quote }}
  CHALLENGE_STORAGE_BACKEND: {{ .Values.config.challengeStorageBackend | quote }}
  REDIS_DB: {{ .Values.config.redisDb | quote }}
  REDIS_TTL_SECONDS: {{ .Values.config.redisTtlSeconds | quote }}
  API_HOST: "0.0.0.0"
  API_PORT: {{ .Values.servicePorts.gateway | quote }}
  GAME_SERVICE_HOST: "0.0.0.0"
  GAME_SERVICE_PORT: {{ .Values.servicePorts.game | quote }}
  CATALOG_SERVICE_HOST: "0.0.0.0"
  CATALOG_SERVICE_PORT: {{ .Values.servicePorts.catalog | quote }}
  RENDER_SERVICE_HOST: "0.0.0.0"
  RENDER_SERVICE_PORT: {{ .Values.servicePorts.render | quote }}
  FRONTEND_HOST: "0.0.0.0"
  FRONTEND_PORT: {{ .Values.servicePorts.frontend | quote }}
  GAME_SERVICE_BASE_URL: "http://{{ include \"blurmoji.fullname\" . }}-game:{{ .Values.servicePorts.game }}"
  CATALOG_SERVICE_BASE_URL: "http://{{ include \"blurmoji.fullname\" . }}-catalog:{{ .Values.servicePorts.catalog }}"
  RENDER_SERVICE_BASE_URL: "http://{{ include \"blurmoji.fullname\" . }}-render:{{ .Values.servicePorts.render }}"
  API_BASE_URL: "http://{{ include \"blurmoji.fullname\" . }}-gateway:{{ .Values.servicePorts.gateway }}"
  REDIS_HOST: "{{ include \"blurmoji.fullname\" . }}-redis"
  REDIS_PORT: {{ .Values.servicePorts.redis | quote }}

