apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "blurmoji.fullname" . }}-mysql-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.mysqlSize }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "blurmoji.fullname" . }}-azurite-pvc
  namespace: {{ .Values.global.namespace }}
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: {{ .Values.persistence.azuriteSize }}

