apiVersion: v1
kind: Service
metadata:
  name: {{ include "blurmoji.fullname" . }}-redis
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ include "blurmoji.fullname" . }}-redis
  ports:
    - port: {{ .Values.servicePorts.redis }}
      targetPort: {{ .Values.servicePorts.redis }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blurmoji.fullname" . }}-mysql
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ include "blurmoji.fullname" . }}-mysql
  ports:
    - port: {{ .Values.servicePorts.mysql }}
      targetPort: {{ .Values.servicePorts.mysql }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "blurmoji.fullname" . }}-azurite
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ include "blurmoji.fullname" . }}-azurite
  ports:
    - port: {{ .Values.servicePorts.azurite }}
      targetPort: {{ .Values.servicePorts.azurite }}

